# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.3.0.app
    - name: Build iOS
      run: xcodebuild build -scheme AppScreenshotKit-Package -destination generic/platform=iOS
    - name: Test iOS
      run: echo "Testing iOS" # Placeholder for iOS tests
    - name: Test CLI
      run: swift test --filter AppScreenshotKitCLITests 
